### ISSUE TITLE
Minimum python supported is 3.7

### ISSUE THREAD

**Issue by mbhall88** [leoisl/make_prg#6]
The docs state that to install locally, you need python>=3. However, as you rely on numpy==1.20.0

https://github.com/leoisl/make_prg/blob/86414544e9da5fdb535d1277e9695e7ffa169fd9/setup.py#L14

the [minimum supported version by that numpy version is 3.7](https://numpy.org/doc/stable/release/1.20.0-notes.html)

**Comment by leoisl** [comment]
Thanks, fixed: https://github.com/leoisl/make_prg/commit/4b651bf1e84321bd4b5e71eb53bd5926ab2fe991
