### ISSUE TITLE
Send logging to stderr

### ISSUE THREAD

**Issue by mbhall88** [leoisl/make_prg#7]
It's kind of annoying having logging go to a mixture of stderr and stdout...

Maybe look at using https://github.com/Delgan/loguru if you want "thread-safe" logging?

**Comment by mbhall88** [comment]
> It's kind of annoying having logging go to a mixture of stdout and stderr...
> 
> Maybe look at using https://github.com/Delgan/loguru if you want "thread-safe" logging?

**Comment by leoisl** [comment]
Closed via https://github.com/leoisl/make_prg/pull/8
